Enforce code style on doc comments #156
rosenpass/rosenpass pull request #158
Opened 2023-11-20 13:32 UTC by alankritdabral

Summary: 
Added style.sh file that use cargo +stable fmt for Rust code formatting.
The script continues to leverage Prettier for formatting other file types such as GraphQL, YAML, JSON, and Markdown.
to run style.sh you can  use ./style.sh --mode=fix and to check ./style.sh --mode=check

Added ci.yml : this  workflow triggers to run on pushes to the main branch, pull requests (opened or synchronized), and published releases.

Issue References:
Fixes: #156 
/claim #156

2023-11-20 13:55 UTC, alankritdabral commented
@koraa can you tell me if this approach is correct

2023-11-22 14:55 UTC, alankritdabral commented
@koraa

2023-11-24 06:44 UTC, ologbonowiwi requested changes
IMO it also needs to be checked  if the project will actually use prettier or if it'll use other tooling to handle it. 

I know you took inspiration from tailcallhq/tailcall, but every project has different needs and we could have checked with @koraa if this is the desired approach _before_ working on the implementation.

2023-11-24 06:44 UTC, ologbonowiwi commented on .github/workflows/ci.yml
> +name: Run Formater
Can you change this file name to `lint.yml`? It'd make more sense as has no continuous integration related stuff on it.

2023-11-26 09:58 UTC, koraa commented
/tip 10

2023-11-26 10:07 UTC, alankritdabral commented
> /tip 10

Thank you for  the tip. Should i close the pr as @Min2who wants to get it assigned or should i keep working on it

2023-11-26 10:12 UTC, koraa commented
> > /tip 10
> 
> Thank you for the tip. Should i close the pr as @Min2who wants to get it assigned or should i keep working on it

You are invited to keep working on this or collaborate with @ologbonowiwi or @Min2who or both and if the bounty is low or all three of you want to share in the bounty, I can raise it a bit too (in this case you would have to post a bid in this issue); I am sure either could help you figure out how to tackle this issue.

I'd rather enable people to work on issues than get bogged down by assigning ownership :)

The basic two steps to (1) format examples in the readme and (2) format examples in doc comments can be tackled in parallel anyway!

2023-12-01 15:05 UTC, koraa commented
@alankritdabral Do you intend to finish this project?

2023-12-01 15:14 UTC, alankritdabral commented
> @alankritdabral Do you intend to finish this project?
Well i have one approach in mind will be pushing some commits tomorrow. Sorry for the delay 🙏🏻😔😔.

2023-12-03 10:27 UTC, alankritdabral commented
@koraa can you take a look in the code changes you can even run locally

2023-12-03 11:29 UTC, wucke13 commented on format_rust_code.sh
> +#!/bin/bash
Please use `#!/usr/bin/env bash`.

2023-12-03 11:36 UTC, wucke13 commented
The approach doesn't yet work (but it can be fixed!).

1. If there is a formatting error, please make sure that the CI job fails. Best case you set an internal variable, but keep checking all files, and only after all files have been checked return the 0 if no error was found or 1 if at least one file violates the formatting.
2. Some rust doc code directly starts with `let var = ...`. This is detected as a syntax error. You have to enclose this into a `fn my_fn(){ }` or something similar to make sure that you don't get syntax errors from `rustfmt`.

2023-12-04 18:32 UTC, alankritdabral commented
@wucke13 can you run the workflow and review it 
if want to run it locally you can run bash format_rust_code.sh --mode fix

2023-12-06 07:49 UTC, alankritdabral commented
@wucke13 🤓

2023-12-10 15:12 UTC, koraa commented
Hi @alankritdabral,

this is pretty hacky…but also pretty cool. It only solves half of the issue – i.e. formatting examples in markdown code while disregarding markdown code in rustdoc but be that as it may, I am happy to merge this and award the bounty for just that improvement.

If I run `--fix` and then `--check`, check still reports issues, can you fix that?

> @wucke13 what to do with non-utf8 codes rustfmt cant deal with it should i just ignore non-utf8 ??

Can you elaborate on what you mean by non-utf8? All our source files should be utf8-encoded.

2023-12-11 12:28 UTC, alankritdabral commented
> If I run `--fix` and then `--check`, check still reports issues, can you fix that?

i have fixed this issue will be pushing in a new pr

2023-12-11 12:32 UTC, alankritdabral commented
> Can you elaborate on what you mean by non-utf8? All our source files should be utf8-encoded.

well it was a mistake from my side thee  code was treating  anything inside fence  code with `\` as a escape sequence so it was giving an error as non valid utf code i am almost done with this issue

2023-12-12 15:44 UTC, alankritdabral commented
@koraa i have tested the file now its working fine

2023-12-17 08:01 UTC, alankritdabral commented
@koraa

2023-12-22 16:49 UTC, wucke13 commented
@alankritdabral I took the liberty to squash your commits and apply the tool as well. Thank you for your contribution!

2023-12-22 16:52 UTC, alankritdabral commented
> @alankritdabral I took the liberty to squash your commits and apply the tool as well. Thank you for your contribution!

just wanted to know if there is any community for the rosenpass for eg ddiscord?

2023-12-22 16:57 UTC, wucke13 approved these changes

2023-12-22 16:57 UTC, merged

2024-01-16 18:12 UTC, koraa commented
> > @alankritdabral I took the liberty to squash your commits and apply the tool as well. Thank you for your contribution!
> 
> just wanted to know if there is any community for the rosenpass for eg ddiscord?

Yes there is, you would be most welcome to join our matrix developer chat :)

https://matrix.to/#/#rosenpass-dev:matrix.org