Move static KEM public key to new PublicBox struct
rosenpass/rosenpass pull request #350
Opened 2024-06-17 04:58 UTC by pqcfox

This PR moves the McEliece public key from secret heap memory to public heap memory using a new `PublicBox` struct, lowering the amount of memfd memory used per peer when using memfd-based allocation.

(Original discussion for this change took place in #341.)

2024-06-17 11:29 UTC, koraa approved these changes

2024-06-17 11:29 UTC, koraa commented on rosenpass/src/protocol.rs
> +                .mix(&*self.spkm)?
Looks all good…how about using .deref() or .borrow() here (as appropriate) to avoid this magic looking incantation?

2024-06-17 11:35 UTC, koraa requested changes
Some of the code seems unnecessarily complex and copy/paste based. Lets write as little code as possible here.

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        (**self).try_fill(&mut crate::rand::rng()).unwrap()
This also looks pretty magic…is there a method alternative for this?

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        mutating(Self::zero(), |r| r.randomize())
I think this can be based on Public::random

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        (**self).try_fill(&mut crate::rand::rng()).unwrap()
Also, this can be based on Public::randomize

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        &**self
These would also look a lot less magic with method style incantations

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        let mut v = Self::random();
This can be based on the Public impl for LoadValue

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        std::fs::write(path, **self)?;
This can be based on the Public impl of StoreValue

2024-06-17 11:35 UTC, koraa commented on secret-memory/src/public.rs
> +        let mut f = [0u8; F];
This can be based on the Public impl of LoadValueB64

2024-06-17 11:57 UTC, koraa commented
@pqcfox I simplified a few of the dereferencing incantations in PublicBox

2024-06-17 12:07 UTC, koraa requested changes

2024-06-17 12:07 UTC, koraa commented on secret-memory/src/public.rs
> +        let mut f = [0u8; F];
OK so there is actually some good reason to have this be a separate implementation: Avoiding large stack allocation.

Unfortunately the `let mut f = [0u8; F];` will break this. If we replace this with a heap allocation this all will make sense again!

2024-06-17 12:09 UTC, koraa commented
> ## [Codecov](https://app.codecov.io/gh/rosenpass/rosenpass/pull/350?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass) Report
> 
> Attention: Patch coverage is `45.09804%` with `56 lines` in your changes missing coverage. Please review.
> 
> > Project coverage is 73.92%. Comparing base [(`7c54a37`)](https://app.codecov.io/gh/rosenpass/rosenpass/commit/7c54a37618dbdfe639f19401809d4bd594d1d64e?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass) to head [(`2eefab2`)](https://app.codecov.io/gh/rosenpass/rosenpass/commit/2eefab265bf65b7c8904849c6a5b3d108e1ec61d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass).
> 
> [Files](https://app.codecov.io/gh/rosenpass/rosenpass/pull/350?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass) 	Patch % 	Lines
> [secret-memory/src/public.rs](https://app.codecov.io/gh/rosenpass/rosenpass/pull/350?src=pr&el=tree&filepath=secret-memory%2Fsrc%2Fpublic.rs&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass#diff-c2VjcmV0LW1lbW9yeS9zcmMvcHVibGljLnJz) 	31.70% 	[56 Missing ⚠️ ](https://app.codecov.io/gh/rosenpass/rosenpass/pull/350?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass)
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/rosenpass/rosenpass/pull/350?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=rosenpass).

@pqcfox Could you also make sure to reuse the `Public` tests?

2024-06-17 14:03 UTC, pqcfox commented
@koraa thanks so much! I'll continue simplifying and add the coverage today.

2024-06-18 03:48 UTC, pqcfox commented
Perfect, made the changes requested @koraa! A couple of small notes:

- For one, the stack allocation comment you made was spot on--in particular the stack overflows during integration tests if I define `PublicBox::load` in terms of `Public::load`, so I wrote it in terms of `PublicBox::zero` instead.
- For `PublicBox::LoadValueB64` and your comment on that it might be useful to avoid excessive stack usage, I opted to use a `vec!` to move the backing memory for the scratch variable `t` to the heap. I also considered `Box::new([0u8; N])`, but I realized that that would still end up allocating stack space, and I wanted to avoid having to use unstable features like `Box::new_zeroed()` if possible.

Let me know your thoughts, thanks so much for the excellent feedback!

2024-06-21 11:07 UTC, merged

2024-06-21 11:08 UTC, koraa commented
@pqcfox Its great :)

2024-06-21 11:13 UTC, pqcfox commented
Thanks! Excited to have this merged!