fix(dualstack): logic error in IPv4 socket creation
rosenpass/rosenpass pull request #465
Opened 2024-10-30 10:01 UTC by aparcar

This commit fixes a logic error in the socket creation for v6 and v4. The error case is that an IPv6 only socket would prevent an additional IPv4 socket to be created.

With this commit each variable it's made sure that at least a dualstack IPv6 socket exists or an IPv4 and IPv6 socket.

Special case is macOS, while they report to support dualsocket, in fact it doesn't work.

Move the logic to it's own function and add some test cases.

Fixes: https://github.com/rosenpass/rosenpass/issues/448

2024-10-30 18:32 UTC, KarlK90 reviewed
Hi @aparcar,

This change alters the default behavior of rosenpass IMHO unexpected ways e.g.: If I want to only listen on the IPv6 loopback interface on port 9998 by setting `listen = ["[::1]:9998"]` I now get a IPv4 socket which listens on all interfaces as well, possibly exposing it on interfaces I don't want it exposed.

After giving it some thought I do believe that the previous behavior is in fact correct - just that rosenpass should provide more hints how it is reachable on startup - possibly with a table which indicates which sockets are ipv4/ipv6/dual-stack so it is more obvious why a connection attempt might not succeed.

2024-10-30 18:50 UTC, KarlK90 requested changes

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +    });
This block is almost verbatim repeated in `helper_support_ipv4_ipv6` it could be a helper function which is shared between tests and actual code.

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +        log::debug!("Register IPv4 socket as fallback.");
If the change in behavior is accepted in rosenpass - I would promote it to `info!` and give it a descriptive text explaining why the ipv4 socket was registered.

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +        let addr = s.local_addr().unwrap();
Please replace the `unwrap()` call by skipping this socket.

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +        log::debug!("Register IPv6 socket as fallback.");
Same here.

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +            .unwrap(),
```suggestion
        sockets.push(UdpSocket::bind("127.0.0.1:0".parse().unwrap()).unwrap());
```

Nit, IMHO this is more readable. Same for the IPv6 case.

2024-10-30 18:50 UTC, KarlK90 commented on rosenpass/src/app_server.rs
> +        let _ = open_sockets(&mut sockets);
```suggestion
        assert!(open_sockets(&mut sockets).is_ok());
```

You probably want to test that your function didn't error out early.

2024-11-04 14:45 UTC, aparcar commented
First of, there seem to be a logic flaw in the current implementation. The need for a v4 socket is only evaluated if no `listen` address is defined at all. The functionality is "hidden" in the `is_empty()` block, see [here](https://github.com/rosenpass/rosenpass/blob/main/rosenpass/src/app_server.rs#L601). This renders Rosenpass broken for configuration like described by @tfc. 

Looking at the WireGuard [Kernel](https://github.com/torvalds/linux/blob/master/drivers/net/wireguard/socket.c#L20) and [Rust](https://github.com/cloudflare/boringtun/blob/64a2fc7c63e5f5a9aa5b8e1fbcefd504778ad118/boringtun/src/device/peer.rs#L123) implementation, both listen on any IPv4 and IPv6 port by default. Since, just like WireGuard, Rosenpass must not respond to anything but valid messages, containing message data encrypted with the receivers public key, it looks like the same "expose" level to me.

To my understanding we're facing the following problem which isn't even super unlikely: A user defines a remote server as peer available over IPv6 and IPv4. Later the user adds an IPv4 listen address and thereby looses IPv6 connectivity to remote peers. This behavior seems rather confusing and therefore I suggest to decouple both logics entirely. After all, it's an outgoing socket to reach remote peers, Mio shouldn't even accept initiation messages there.

2026-05-13 07:22 UTC, closed without merging

2026-05-13 07:22 UTC, ilka-schulz commented
closed due to inactivity