Add documentation, doc-tests and examples to the secret-memory crate.
rosenpass/rosenpass pull request #531
Opened 2024-12-13 13:39 UTC by DavidNiehues

2024-12-14 09:38 UTC, DavidNiehues commented
> @DavidNiehues Can you add some more unit tests to drive up the coverage?

Sure! I took a close look at the codecov report. I see potential for actual higher coverage in `public.rs` and `secret.rs`. According to codecov, there still some uncovered functions in `malloc.rs`, `memfdsec.rs` and `alloc/mod.rs` that actually have doc-tests right above them that cover them but aren't detected as such by codecov.

2024-12-14 11:16 UTC, DavidNiehues commented
@koraa I now added more unit tests for `secret.rs` and `public.rs`.

2024-12-16 16:21 UTC, DavidNiehues commented
@koraa @aparcar I made the same style change around doc-tests with the `?`-operator and rebased onto main here as well.

2024-12-18 09:37 UTC, aparcar commented on secret-memory/src/secret.rs
> +    /// Relaases the memory of this [ZeroizingSecretBox]. In contrast to usual implementations
Typo

2024-12-18 09:40 UTC, aparcar commented on secret-memory/src/secret.rs
> +/// my_secret.zeroize();
If it's randomized anyway, should the documentation motivate users to actively do it? This seems to add extra randomization steps where there are not needed. Don't we trust our automatic zeroing step?

2024-12-18 09:41 UTC, aparcar commented on secret-memory/src/secret.rs
> +    /// Relaases the memory of this [Secret]. In contrast to usual implementations to [Drop] we
Typo

2024-12-18 09:42 UTC, aparcar commented on secret-memory/src/secret.rs
> +// Indicate that a Secret is always zeroized when it is dropped.
Missing brackets around Secret?

2024-12-18 09:43 UTC, aparcar commented
Thanks again for your work, I think this is mostly ready except some minor things!

2024-12-18 13:11 UTC, aparcar requested changes
Please fix the remaining typos and I'm happy to merge this.

2024-12-18 15:18 UTC, aparcar approved these changes

2024-12-18 15:18 UTC, merged